<div>
  <h3>Create your account with us</h3>
</div>
<div>
  <form action="/accounts/create" method="post">
    <div>
      Name:<br/>
      <input type="text" name="name"/>
      <br/>
      <br/>
      Email:<br/>
      <input type="text" name="email"/>
      <br/>
      <br/>
      Password:<br/>
      <input type="password" name="password"/>
      <br/>
      <br/>
      <input type="submit" value="Create Account"/>
    </div>
  </form>
</div>